EXPRESS VISITS
FEMALE Express
XX yr old female Pt presents to clinic for STD screening. Pt denies any symptoms; no clinician assessment performed. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing. Urine pregnancy test obtained to rule out pregnancy. Stat RPR today was non-reactive; reviewed negative RPR result with Pt and a hard copy was provided. Pregnancy test was negative, hard copy was provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 15 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
HETEROSEXUAL MALE Express
XX yr old heterosexual male Pt presents to clinic for STD screening. Pt denies any symptoms; no clinician assessment performed. Blood collected for HIV/RPR screening; urine collected for GC/CT testing. Stat RPR today was non-reactive; reviewed negative RPR result with Pt and a hard copy was provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 15 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
ASYMPTOMATIC (MSM – non-reactive RPR) 
XX yr old MSM presents to clinic for STD screening. Pt denies any symptoms at this time and is seeking routine testing. Blood collected for HIV/RPR syphilis testing; urine, throat and rectal swabs were collected for GC/CT screening. Per clinician assessment, no signs of STDs were evidenced. Stat RPR today was non-reactive. Reviewed negative RPR results with patient and a hard copy was provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest every 3-6 months (or PRN) per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 15 minutes on PE, reviewing patient's chart/medical history, formulating POC, and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs/PrEP).




TOC- MSM
MSM TEST OF CURE (TOC)
XX yr old MSM presents to clinic for STD screening. Pt denies any symptoms at this time and is here for TOC; Pt was treated for oropharyngeal GC at last visit. Throat swab was collected for GC/CT screening. No clinician assessment, Pt denies any new sexual contact since prior to last testing/tx. Educated Pt on STD prevention strategies including consistent condom usage and to retest every 3-6 months (or PRN) per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, formulating POC, and answering questions. Spent 10 minutes on education (safe sex, consistent condom use, STDs).



RESULTS ONLY- NORMAL
Female results 
XX yr old female presents to clinic for results review from initial visit on XX /XX /20XX. Pt states no symptoms today. Reviewed results with Pt and provided hard copies. Reviewed STD prevention strategies such as consistent condom usage. Pt aware to RTC to retest annually (or PRN) per CDC recommendations. Patient voiced understanding of results and education. Spent 35 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
HETEROSEXUAL MALE results 
XX yr old heterosexual male presents to clinic for results review from initial visit on XX/XX  /20XX. Pt states no symptoms today. Reviewed results with Pt and provided hard copies. Reviewed STD prevention strategies such as consistent condom usage. Pt aware to RTC to retest annually (or PRN) per CDC recommendations. Patient voiced understanding of results and education. Spent 35 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
MSM results
XX yr old MSM presents to clinic for results review from initial visit on XX/XX//20XX. Pt states no symptoms today. Reviewed results with Pt and provided hard copies. Reviewed STD prevention strategies such as consistent condom usage. Pt aware to RTC in 3-6 months to retest per CDC recommendations. Patient voiced understanding of results and education. Spent 35 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
MSM results and TOC
XX yr old MSM presents to clinic for results from initial visit on XX/XX/20XX and TOC. Pt states no symptoms today. Reviewed results with Pt and provided hard copies. Throat swab was collected for TOC - GC/CT screening at this time. Pt was treated for oropharyngeal GC at last visit. No RN assessment. Educated Pt on STD prevention strategies including condom usage. Pt to RTC in 2 weeks for review of TOC results. Pt voiced understanding of education and agrees with plan of care. Spent 35 minutes reviewing patient's chart/medical history, collecting specimen, formulating POC, and answering questions. Spent 10 minutes on education (safe sex, consistent condom use, STDs).



RESULTS – ABNORMAL/TREATMENTS
Female/MALE/MSM results (CT treatment - DOXY)
XX yr old presents to clinic for results review from initial visit on XX/XX/20XX and chlamydia treatment. Reviewed results with Pt and hard copies were provided. Notified Pt of need for treatment for positive CT results per SDOs. Pt agreed and received doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Reviewed STD prevention strategies including consistent condom usage. CT CDC fact sheet provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Pt voiced understanding of education and agrees with plan of care. Spent 35 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
Female/MALE/MSM results (CT and GC treatment - DOXY)
 XX yr old presents to clinic for results review from initial visit on XX/XX/20XX and chlamydia/gonorrhea treatment. Reviewed results with Pt and hard copies were provided. Notified Pt of need for CT/GC treatment per SDOs. Pt agreed and received doxycycline 100 mg PO BID x7 days and Ceftriaxone 500 mg, IM was administered to the deltoid; Pt tolerated injection well. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Reviewed STD prevention strategies including consistent condom usage and need for Pt to notify partner/partners from the last 2 months to get tested and treated. CT & GC CDC fact sheets provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Pt voiced understanding of education and agrees with plan of care. Spent 35 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
Female results (CT treatment - AZITHRO)
XX yr old presents to clinic for results review from initial visit on XX/XX/20XX and chlamydia treatment. Reviewed results with Pt and hard copies were provided. Notified Pt of need for CT treatment per SDOs. Pt agreed and azithromycin 1 gm PO stat dose was administered to Pt at this time. Doxycycline was not provided because pregnancy could not be ruled out at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. CT CDC fact sheet provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Pt voiced understanding of education and agrees with plan of care. Spent 35 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
Female results (CT AND GC treatment - AZITHRO)
XX yr old female presents to clinic for results review from initial visit on XX/XX/20XX and chlamydia/gonorrhea treatment. Reviewed results with Pt and hard copies were provided. Notified Pt of need for CT/GC treatment per SDOs. Pt agreed and azithromycin 1 gm PO stat dose was administered to Pt at this time. Doxycycline was not provided because pregnancy could not be ruled out at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Ceftriaxone 500 mg, IM was administered to the deltoid; Pt tolerated injection well. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. CT & GC CDC fact sheets provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
Female/MALE/MSM results (GC treatment)
XX yr old presents to clinic for results review from initial visit on XX/XX/20XX and gonorrhea treatment. Reviewed results with Pt and hard copies were provided. Notified Pt of need for GC treatment per SDOs. Pt agreed and Ceftriaxone 500 mg, IM was administered to the     deltoid; Pt tolerated injection well. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. GC CDC fact sheet provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
MSM External Records Results (GC treatment)
yr old MSM presents to clinic for results review from Austin clinic visit on 03/2025, gonorrhea treatment and STD screening. Blood collected for RPR/HIV screening and urine, throat and rectal swabs also collected for GC/CT screening. Reviewed nonreactive RPR results with Pt and reviewed external results with positive rectal Gonorrhea results. Notified Pt of need for GC treatment. Pt agreed and Ceftriaxone 500 mg, IM was administered to the right deltoid; Pt tolerated injection well. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. GC CDC fact sheet provided. Educated Pt to notify partner(s) from the last 2 months to come in to get tested and treated, and to RTC in 3 months to retest per CDC recommendations. Clinic will contact patient for any positive results. Discussed PrEP with Pt. He stated he is interested in PrEP and was provided with a referral and resource list for PrEP clinic with Centro San Vicente.  Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs). 

FEMALE with BV
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt C/O discharge and odor x1 month. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, urine pregnancy test obtained to rule out pregnancy and wet mount collected for BV/trich/yeast screening.  Per clinician assessment; small white thin discharge, odorous, pH 5.5, per lab: no yeast, no trich, clue cells found (4 of 4 criteria met for bacterial vaginosis). Reviewed abnormal wet mount results, negative pregnancy test, and non-reactive RPR results with Pt. Notified Pt per SDOs, she may receive treatment for meeting BV criteria. Pt agreed and received metronidazole 500 mg PO BID x7 days. Reviewed need for patient to take medication with food and to avoid sexual contact X7 days and ETOH x10 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV CDC fact sheet provided. Instructed patient to avoid vaginal wipes, soaps, or douching, and to avoid thong underwear. Educated Pt on prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 7-10 days for hard copy of results as needed. Clinic will contact Pt to notify of any positive results.  Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE with BV AND YEAST - (FLUCONAZOLE PROVIDED)
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt is seeking routine STD testing and C/O vaginal itching and discharge. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, urine HCG obtained to rule out pregnancy, and wet mount collected for BV/trich/yeast screening. Per clinician assessment; moderate yellow discharge, odorous, pH 6.0, per lab: yeast found, no trich, clue cells found - 4 of 4 criteria met for bacterial vaginosis). Reviewed abnormal wet mount results, negative pregnancy test, and non-reactive RPR results with Pt. Notified Pt per SDOs, she may receive treatment for BV and yeast. Pt agreed and received metronidazole 500 mg PO BID X7 days. Fluconazole 150 mg PO stat dose was administered at this time. Pt tolerated medication well. Reviewed possible side effects with patient (headache, nausea, abdominal pain). Pt educated to refrain from sexual contact x7 days and ETOH x10 days. BV and yeast CDC fact sheets provided. Instructed patient to avoid vaginal wipes, soaps, douching, and thong underwear to prevent recurrent or future vaginal infections. Patient stated understanding. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Pt to RTC in 7-10 days for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart, obtaining medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs).
FEMALE with BV and YEAST (OTC – MICONAZOLE RECOMMENDED)
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt is seeking routine STD testing and C/O odor with intercourse. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; minimal amount of white thick discharge, odorous, pH 5.5, per lab: yeast found, no trich, clue cells found - 4 of 4 criteria met for bacterial vaginosis). Reviewed abnormal wet mount and non-reactive RPR results with Pt, hard copies were provided. Notified Pt per SDOs, she may receive treatment for BV and OTC antifungal (miconazole) recommended x5-7 days for yeast. Pt agreed and received metronidazole 500 mg PO BID x7 days. Pt educated to refrain from sexual contact x14 days and ETOH X8 days. BV and yeast CDC fact sheets provided. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE with YEAST - (FLUCONAZOLE PROVIDED)
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt is seeking routine STD testing and C/O vaginal discharge and itching x3 days. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, urine HCG obtained to rule out pregnancy, and wet mount collected for BV/trich/yeast screening. Per clinician assessment; moderate white curdy discharge, non-odorous, pH 4.5, per lab: yeast found, no trich, no clue cells. Reviewed abnormal wet mount results and non-reactive RPR results with Pt. Notified Pt she may receive treatment for yeast. Pt agreed and Fluconazole 150 mg PO stat dose was administered at this time. Pt tolerated medication well. Reviewed possible side effects with patient (headache, nausea, abdominal pain). Pt educated to refrain from sexual contact until clear. Yeast CDC fact sheet provided. Instructed patient to avoid vaginal wipes, soaps, vaginal douching, or tight fitted clothing. She was also instructed to avoid thong underwear. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Clinic will contact Pt to notify of any positive results. Pt voiced understanding of education and agrees with plan of care. Spent minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs). -E. Gutierrez, NP.
FEMALE with YEAST (OTC – MICONAZOLE RECOMMENDED)
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt is seeking routine STD testing and C/O vaginal odor prior, but subsided. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; moderate white thick discharge, non-odorous, pH 4.5, per lab: yeast found, no trich, no clue cells. Reviewed abnormal wet mount results and non-reactive RPR results with Pt, hard copies were provided. Notified Pt per SDOs, OTC antifungal (miconazole) recommended x5-7 days. Yeast CDC fact sheet provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Clinic will contact Pt to notify of any positive results. Pt voiced understanding of education and agrees with plan of care. Spent 15 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).

FEMALE with Trichomoniasis
XX  yr old female Pt presents to clinic for STD screening. Pt is C/O vaginal discharge, and pruritus x3 weeks ago, she also reports exposure to trichomoniasis. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Urine pregnancy test obtained. Per RN assessment: moderate yellow vaginal discharge, odorous, pH 6.5, per lab - trichomoniasis found, no yeast, no clue cells (3 of 4 criteria met for BV). Reviewed abnormal wet mount results with Pt. Notified Pt she may receive treatment for trichomoniasis. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Trichomoniasis CDC fact sheet provided. Pt to RTC in 7-10 days with ID for hardcopy of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis (TX’D WITH DOXYCYCLINE AND CEFT)
XX yr old female Pt presents to clinic for STD screening/retesting Pt is seeking routine STD testing and C/O. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; copious yellow mucous discharge, pH 4.5, odorous, per lab: no trich, no yeast, no clue cells. Lab stated many bacteria was seen. Stat RPR today was non-reactive. Reviewed abnormal wet mount results and non-reactive RPR results with Pt. Notified Pt per SDOs, she may receive treatment for mucopurulent cervicitis. Pt agreed and received doxycycline 100 mg PO BID x7 days, and ceftriaxone 500 mg IM (NDC# 0409-7338-01) was administered to deltoid. Pt tolerated injection well. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis (TX’D WITH DOXYCYCLINE, NO CEFT)
XX yr old female Pt presents to clinic for STD screening/retesting Pt is seeking routine STD testing and C/O yellow vaginal discharge and a vaginal burning sensation. Patient reports recently going to Project Vida and was treated for BV and yeast. Patient states only the itching resolved but other symptoms continue. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, urine hcg obtained to rule out pregnancy, and wet mount collected for BV/trich/yeast screening. Per clinician assessment; small pink discharge, friable cervix, pH 6.0, non-odorous, per lab: no trich, no yeast, no clue cells. Lab stated many WBCs was seen. Stat RPR today was non-reactive. Reviewed abnormal wet mount results and non-reactive RPR results with Pt. Notified Pt per SDOs, she may receive treatment for mucopurulent cervicitis. Pt agreed and received doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Pt educated to refrain from sexual contact and ETOH x7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Educated Pt on prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 10-14 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis (TX’D W/AZITHROMYCIN AND CEFT)
XX yr old female Pt presents to clinic for STD screening. Pt is seeking routine STD testing and C/O. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; copious yellow discharge, pH 4.5, odorous, per lab: no trich, no yeast, no clue cells, but many WBCs were seen. Stat RPR today was non-reactive. Reviewed abnormal wet mount results and non-reactive RPR results with Pt. Notified Pt per SDOs, she may receive treatment for mucopurulent cervicitis. Pt agreed and azithromycin 1 gm PO stat dose was administered to Pt at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Ceftriaxone 500 mg IM (NDC# 0409-7338-01) was administered to     deltoid. Pt tolerated injection well. Pt educated to refrain from sexual contact and ETOH X7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Educated Pt on prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 10-14 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis (TX’D W/AZITHROMYCIN ONLY)
XX yr old heterosexual female Pt presents to clinic for STD screening. Pt is C/O vaginal discharge and pruritus X1 week. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; minimal white discharge, pH 5.5, non-odorous, per lab: no trich, no yeast, and clue cells found, moderate WBCs were seen. Stat RPR today was non-reactive. Reviewed wet mount and non-reactive RPR results with Pt and hard copies were provided. Notified Pt per SDOs, she may receive treatment for mucopurulent cervicitis. Pt agreed and azithromycin 1 gm PO stat dose was administered to Pt at this time. Doxycycline was not provided as pregnancy cannot be ruled out at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Pt educated to refrain from sexual contact and ETOH X7 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Cervicitis fact sheet was provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis AND BV (TX’D WITH DOXYCYCLINE ONLY – NO CEFT.)
XX yr old female Pt presents to clinic for STD screening. Pt C/O burning, odor, and itching beginning X1 month ago. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment: copious yellow vaginal discharge, odorous, pH 5.0, per lab - no trichomoniasis, no yeast, clue cells found and many WBCs seen (4 of 4 criteria met for BV). Reviewed non-reactive RPR results and abnormal wet mount results with Pt, a hard copy of both was provided. Notified Pt per SDOs, she may receive treatment for BV and mucopurulent cervicitis. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days, and doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV CDC fact sheet provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis AND BV (TX’D WITH AZITHROMYCIN ONLY - NO CEFT.)
XX yr old female Pt presents to clinic for STD screening. Pt is C/O vaginal discharge and slight odor x15 days. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment on wet mount: copious yellow vaginal discharge, odorous, pH 5.0, per lab - no trichomoniasis, no yeast, no clue cells found and many WBCs seen (3 of 4 criteria met for BV). Reviewed non-reactive RPR results and abnormal wet mount results with Pt, a hard copy of both results was provided. Notified Pt per SDOs, she may receive treatment for BV and mucopurulent cervicitis. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Azithromycin 1 gm PO stat dose was administered to Pt at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Reviewed need for patient to avoid sexual contact x14 days and ETOH X8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV CDC fact sheet provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Clinic will contact Pt to notify of any positive results. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).
FEMALE WITH Mucopurulent Cervicitis AND BV (TX’D WITH AZITHROMYCIN AND CEFT. IM
XX yr old female Pt presents to clinic for STD screening. Pt is C/O burning sensation & odor     x 3-4 weeks. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment; moderate grey thin discharge, odorous, pH 5.0, per lab: no trich, no yeast, no clue cells, but many WBCs were seen (10+). Reviewed abnormal wet mount results with Pt. Notified Pt per SDOs, she may receive treatment for BV and mucopurulent cervicitis. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Azithromycin 1 gm PO stat dose was administered to Pt at this time. Ceftriaxone 500 mg IM was administered to deltoid. Pt tolerated injection well. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV CDC fact sheet provided. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).

Female Symptomatic With BV & CT EXPOSURE TX (TX’D WITH DOXYCYCLINE)
XX yr old female presents to clinic for STD screening. Pt is C/O vaginal discharge, pruritus and odor x1 week and she reports exposure to chlamydia. Blood collected for HIV/RPR testing, vaginal swab for CT/GC screening, and wet mount for BV/Trich/Yeast testing was collected. Per RN assessment, moderate thin, grey vaginal discharge, odorous, and pH of 5.0 was noted; per lab clue cells were found. Reviewed abnormal wet mount results with Pt (4 of 4 criteria met for BV) and non-reactive stat RPR, hard copies were provided. Notified Pt per SDOs, she may receive treatment for BV and exposure to CT. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days and doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV and Chlamydia CDC fact sheets provided. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).

Female Symptomatic With BV & CT EXPOSURE TX (TX’D WITH AZITHROMYCIN)
XX yr old female presents to clinic for STD screening. Pt is seeking routine STD testing. Pt C/O vaginal itching and odorous vaginal discharge x1 month and states exposure to chlamydia. Blood collected for HIV/RPR testing, vaginal swab for CT/GC screening, and wet mount for BV/Trich/Yeast testing was collected. Per RN assessment, copious thin, grey vaginal discharge, odorous, and pH of 6.5 was noted; per lab clue cells were found. Reviewed abnormal wet mount results with Pt (4 of 4 criteria met for BV). Notified Pt of abnormal wet mount results and non-reactive stat RPR. Notified Pt per SDOs, she may receive treatment for BV and exposure to CT. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Azithromycin 1 gm PO stat dose was administered to Pt at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV and Chlamydia CDC fact sheets provided. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).

Female Symptomatic With BV WITH GC & CT EXPOSURE TX (TX’D WITH DOXY)
XX yr old heterosexual female presents to clinic for STD screening. Pt is seeking routine STD testing and is C/O vaginal discharge and odor x2 days; she denies pruritus or pain. She reports exposure to chlamydia and gonorrhea. Blood collected for HIV/RPR testing, urine HCG obtained to rule out pregnancy, vaginal swab for CT/GC screening, and wet mount for BV/Trich/Yeast testing was collected. Per clinician assessment, minimal white discharge, pH 5.5, odorous. Per lab, clue cells seen, no trichomoniasis, no yeast. Reviewed abnormal wet mount results with Pt (4 of 4 criteria met for BV). Notified Pt of abnormal wet mount results, negative pregnancy test, and non-reactive stat RPR result, hard copies of results were provided. Notified Pt per SDOs, she may receive treatment for BV and exposure to chlamydia and gonorrhea. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Ceftriaxone 500 mg IM was administered to the left deltoid, Pt tolerated injection well. Pt also received doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Reviewed need for patient to avoid sexual contact x14 days and ETOH X10 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV, Chlamydia and gonorrhea CDC fact sheets were provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Clinic will contact Pt to notify of any positive results. Pt voiced understanding of education and agrees with plan of care. Spent 30 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 10 minutes on education (safe sex, condom use, STDs). 

Female Symptomatic With BV WITH GC & CT EXPOSURE TX (TX’D WITH AZITHROMYCIN)
XX yr old heterosexual female presents to clinic for STD screening. Pt is seeking routine STD testing and is C/O vaginal discharge and odor x2 weeks; she denies pruritus or pain. She reports exposure to chlamydia and gonorrhea. Blood collected for HIV/RPR testing, vaginal swab for CT/GC screening, and wet mount for BV/Trich/Yeast testing was collected. Per RN assessment, minimal yellow discharge, pH 5.5, odorous. Per lab, clue cells and many WBCs were seen, no trichomoniasis, no yeast. Reviewed abnormal wet mount results with Pt (4 of 4 criteria met for BV). Notified Pt of abnormal wet mount results and non-reactive stat RPR result, hard copies of results were provided. Notified Pt per SDOs, she may receive treatment for BV and exposure to chlamydia and gonorrhea. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Ceftriaxone 500 mg IM was administered to the rt upper outer buttock quadrant, Pt tolerated injection well. Azithromycin 1 gm PO stat dose was administered to Pt; Doxycycline was not provided because pregnancy could not be ruled out at this time. Educated Pt to eat as soon as possible to prevent emesis and to avoid dairy products for the hour following consumption of medication. Pt educated to RTC for another dose of azithromycin if emesis occurs within 45 minutes from consumption. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV, Chlamydia and gonorrhea CDC fact sheets were provided. Educated Pt on STD prevention strategies including consistent condom usage and to retest PRN or annually per CDC recommendations. Pt to RTC in 7-10 days for hard copy of results with an ID as needed. Clinic will contact Pt to notify of any positive results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, collecting specimen, administering treatment, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).

Female Symptomatic With BV & GC EXPOSURE TX
XX yr old female presents to clinic for STD screening. Pt is seeking routine STD testing. Pt C/O vaginal itching and odorous vaginal discharge x1 month and states exposure to gonorrhea. Blood collected for HIV/RPR testing, vaginal swab for CT/GC screening, and wet mount for BV/Trich/Yeast testing was collected. Per RN assessment, copious thin, grey vaginal discharge, odorous, and pH of 6.5 was noted; per lab clue cells were found. Reviewed abnormal wet mount results with Pt (4 of 4 criteria met for BV). Notified Pt of abnormal wet mount results and non-reactive stat RPR. Notified Pt per SDOs, she may receive treatment for BV and exposure to GC. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days. Ceftriaxone 500 mg, IM was administered to the deltoid; Pt tolerated injection well. Reviewed need for patient to take medication with food and to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV and gonorrhea CDC fact sheets provided. Pt to RTC in 2 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).

Female Symptomatic With BV, TRICHOMONIASIS and MUCOPURELENT CERVICITIS (NO CEFT) (TX’D WITH DOXYCYCLINE)
XX yr old female Pt presents to clinic for STD screening. Pt is C/O burning with urination, odor, vaginal discharge, and pruritus x2 weeks ago. Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing, and wet mount collected for BV/trich/yeast screening. Per RN assessment: copious yellow vaginal discharge, odorous, pH 6.0, per lab - trichomoniasis found, no yeast, no clue cells (3 of 4 criteria met for BV). Reviewed abnormal wet mount results with Pt. Notified Pt per SDOs, she may receive treatment for BV, mucopurulent cervicitis and trichomoniasis. Pt agreed and received treatment with metronidazole 500 mg PO BID x7 days, and doxycycline 100 mg PO BID x7 days. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed pt to wear sun block lotion if exposed to the sun. Reviewed need for patient to avoid sexual contact x14 days and ETOH x8 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. BV and trichomoniasis CDC fact sheet provided. Pt to RTC in 3 weeks for review of results. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 15 minutes on education (safe sex, consistent condom use, STDs).

FEMALE WITH HSV
XX yr old female presents to clinic for STD screening. Pt is C/O bumps to genital area x6 days. Blood collected for HIV/RPR testing and vaginal swab for CT/GC screening. Urine pregnancy test collected to rule out pregnancy. Per RN assessment; multiple herpes lesions noted throughout vulva. Patient states this has never happened to her before, making this her first outbreak. Notified Pt of non-reactive RPR results and negative pregnancy test, she may receive treatment for HSV. Pt agreed and was provided with Valacyclovir 1 gm PO BID x10 days. Pt educated on ER warning signs (rashes, hives, itchiness, shortness of breath).  Pt educated to refrain from sexual contact x10 days/until clear. Herpes pamphlet provided. PT to RTC in 7-10 days for review of result. Pt voiced understanding of education and agrees with plan of care. Spent 35 minutes on PE, reviewing patient's chart/medical history, collecting specimen, formulating POC, administering treatment and answering questions. Spent 10 minutes on education (safe sex, consistent condom use, STDs).

FEMALE WITH PID 
XX yr old female Pt presents to clinic for STD screening. Pt is C/O vaginal discharge, itching, and intermittent pelvic cramping x1 week. Reports having unprotected intercourse before symptoms started.  Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing. Pregnancy test obtained to rule out pregnancy. Wet mount collected for BV/trich/yeast screening. Per clinician assessment; vulvar and vaginal erythema noted, moderate white vaginal discharge, odorous, pH 4.5. Per Lab; no clue cells, no trich, and no yeast, many WBCs and bacteria seen (Pt meets 2 of 4 criteria for BV). Reviewed abnormal wet mount results, negative pregnancy test, and stat non-reactive RPR results with Pt, hard copies were provided. Notified Pt per SDOs, she may receive treatment for PID. Pt agreed and ceftriaxone 500 mg IM was administered to Lt deltoid. Doxycycline 100 mg PO BID x14 days was provided to Pt at this time. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed Pt to wear sun block lotion if exposed to the sun. Reviewed need for patient to avoid sexual contact x14 days and ETOH x15 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Educated Pt on prevention strategies including consistent condom usage. Pt to RTC in 48 hrs. for review of symptoms (Scheduled XX/XX/20XX). If symptoms have not improved and/or worsen, Pt will be referred to the ER. Pt provided with PID CDC fact sheet. Pt voiced understanding of education and agrees with plan of care. Spent 20 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).

FEMALE WITH PID and BV
XX yr old female Pt presents to clinic for STD screening. Pt is C/O vaginal discharge and odor x5 months ago, spotting X1 week, and cramping since this morning.  Blood collected for HIV/RPR screening; vaginal swab collected for GC/CT testing. Wet mount collected for BV/trich/yeast screening. Per RN assessment; moderate grey vaginal discharge, odorous, pH 6.0 (Pt meets 3 of 4 criteria for BV). Reviewed abnormal wet mount results and stat non-reactive RPR results with Pt, hard copies were provided. Notified Pt per SDOs, she may receive treatment for PID and BV. Pt agreed and ceftriaxone 500 mg IM was administered to rt deltoid. Doxycycline 100 mg PO BID x14 days and metronidazole 500 PO BID x14 days was provided to Pt at this time. Educated Pt to eat before taking doxycycline, and to avoid dairy, iron preparations, or antacids for 1 hour before and after taking medications. Reviewed increased risk of photosensitivity while taking doxycycline and instructed Pt to wear sun block lotion if exposed to the sun. Reviewed need for patient to avoid sexual contact x14 days and ETOH x15 days. Reviewed ER warning signs; go to ER if SOB, rashes, hives or itchiness. Educated Pt on prevention strategies including consistent condom usage. Pt to RTC in 48 hrs. for review of symptoms. If symptoms have not improved and/or worsen, Pt will be referred to the ER. Pt provided with PID pamphlet and BV CDC fact sheet. Pt voiced understanding of education and agrees with plan of care. Spent 45 minutes reviewing patient's chart/medical history, formulating POC and answering questions. Spent 15 minutes on education (safe sex, condom use, STDs).
